global:
  # Basic global configuration without external dependencies

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'default-receiver'
    # Default receiver that logs alerts without external dependencies

  - name: 'critical-alerts'
    # Critical alerts logged for now - can be configured later with SMTP/Slack
    
  - name: 'warning-alerts'
    # Warning alerts logged for now - can be configured later with SMTP/Slack

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
