server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
      - json:
          source: attrs
          expressions:
            tag: attrs.tag
      - regex:
          source: tag
          expression: '^.*/(?P<container_name>[^:]+):.*$'
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # System logs
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\w+)\s+(?P<service>\w+)(\[(?P<pid>\d+)\])?\s*:\s*(?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: 'Jan 02 15:04:05'
          location: 'Local'
      - labels:
          hostname:
          service:
          pid:
      - output:
          source: message

  # Nginx access logs
  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-access
          __path__: /var/log/nginx/access.log
    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>\S+)\s+-\s+(?P<remote_user>\S+)\s+\[(?P<time_local>[^\]]+)\]\s+"(?P<method>\S+)\s+(?P<path>\S+)\s+(?P<protocol>\S+)"\s+(?P<status>\d+)\s+(?P<body_bytes_sent>\d+)\s+"(?P<http_referer>[^"]*)"\s+"(?P<http_user_agent>[^"]*)".*$'
      - timestamp:
          source: time_local
          format: '02/Jan/2006:15:04:05 -0700'
      - labels:
          method:
          status:
          remote_addr:
      - output:
          source: message

  # Nginx error logs
  - job_name: nginx-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-error
          __path__: /var/log/nginx/error.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d+/\d+/\d+\s+\d+:\d+:\d+)\s+\[(?P<level>\w+)\]\s+(?P<pid>\d+)#(?P<tid>\d+):\s+(?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: '2006/01/02 15:04:05'
      - labels:
          level:
          pid:
      - output:
          source: message

  # Application-specific logs for different environments
  - job_name: cach-production
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/cach_(.+)_production'
        target_label: 'service'
      - source_labels: ['__meta_docker_container_name']
        regex: '/cach_(.+)_production'
        target_label: 'environment'
        replacement: 'production'
      - source_labels: ['__meta_docker_container_label_service']
        target_label: 'service_type'
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  - job_name: cach-staging
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/cach_(.+)_staging'
        target_label: 'service'
      - source_labels: ['__meta_docker_container_name']
        regex: '/cach_(.+)_staging'
        target_label: 'environment'
        replacement: 'staging'
      - source_labels: ['__meta_docker_container_label_service']
        target_label: 'service_type'
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  - job_name: cach-sandbox
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/cach_(.+)_sandbox'
        target_label: 'service'
      - source_labels: ['__meta_docker_container_name']
        regex: '/cach_(.+)_sandbox'
        target_label: 'environment'
        replacement: 'sandbox'
      - source_labels: ['__meta_docker_container_label_service']
        target_label: 'service_type'
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output