version: '3.8'

services:
  # PostgreSQL Database
  postgres-production:
    image: postgres:15-alpine
    container_name: cach_postgres_production
    environment:
      POSTGRES_DB: cach_db_production
      POSTGRES_USER: cach_user
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_production_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - cach_production_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cach_user -d cach_db_production"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO Object Storage
  minio-production:
    image: minio/minio:latest
    container_name: cach_minio_production
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_production_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - cach_production_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # API Service
  api-production:
    image: abc254/cach-api:production
    container_name: cach_api_production
    environment:
      - ENVIRONMENT=production
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://cach_user:${DATABASE_PASSWORD}@postgres-production:5432/cach_db_production?schema=public
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_USE_SSL=false
      - MINIO_ENDPOINT=minio-production
      - MINIO_PORT=9000
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      - ZOHO_SEND_MAIL_TOKEN=${ZOHO_SEND_MAIL_TOKEN}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - ALLOWED_FILE_TYPES=${ALLOWED_FILE_TYPES}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - LOG_LEVEL=${LOG_LEVEL}
      - API_URL=https://api.cachconnect.co.ke
      - LENDER_APP_URL=${LENDER_APP_URL}
      - DISTRIBUTOR_APP_URL=${DISTRIBUTOR_APP_URL}
      - BUSINESS_APP_URL=${BUSINESS_APP_URL}
      - AGENT_APP_URL=${AGENT_APP_URL}
      - ADMIN_APP_URL=${ADMIN_APP_URL}
    ports:
      - "4000:3001"
    depends_on:
      postgres-production:
        condition: service_healthy
      minio-production:
        condition: service_healthy
    networks:
      - cach_production_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Admin App
  admin-production:
    image: abc254/cach-admin:production
    container_name: cach_admin_production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.cachconnect.co.ke
    ports:
      - "4050:3000"
    networks:
      - cach_production_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Website
  website-production:
    image: abc254/cach-website:production
    container_name: cach_website_production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.cachconnect.co.ke
    ports:
      - "4060:3000"
    networks:
      - cach_production_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Agent App
  agents-production:
    image: abc254/cach-agent:production
    container_name: cach_agents_production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.cachconnect.co.ke
    ports:
      - "4010:3000"
    networks:
      - cach_production_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Distributor App
  distributors-production:
    image: abc254/cach-distributor:production
    container_name: cach_distributors_production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.cachconnect.co.ke
    ports:
      - "4020:3000"
    networks:
      - cach_production_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Business App
  business-production:
    image: abc254/cach-business:production
    container_name: cach_business_production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.cachconnect.co.ke
    ports:
      - "4030:3000"
    networks:
      - cach_production_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Lender App
  lenders-production:
    image: abc254/cach-lender:production
    container_name: cach_lenders_production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.cachconnect.co.ke
    ports:
      - "4040:3000"
    networks:
      - cach_production_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_production_data:
    driver: local
  minio_production_data:
    driver: local

networks:
  cach_production_network:
    external: true
    name: cach_production_network