server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker containers
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging']
        target_label: 'logging'
      # Extract environment from container name
      - source_labels: ['__meta_docker_container_name']
        regex: '.+-(production|staging|sandbox).*'
        target_label: 'environment'
        replacement: '${1}'
      # Extract app type from container name
      - source_labels: ['__meta_docker_container_name']
        regex: 'cach-([^-]+)-.*'
        target_label: 'app'
        replacement: '${1}'

  # Nginx access logs
  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-access
          __path__: /var/log/nginx/access.log
    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>[\d\.]+) - (?P<remote_user>[^ ]*) \[(?P<time_local>[^\]]*)\] "(?P<method>[A-Z]+) (?P<request_uri>[^ ]*) HTTP/[^"]*" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"'
      - labels:
          remote_addr:
          method:
          request_uri:
          status:
          http_referer:
      - timestamp:
          source: time_local
          format: 02/Jan/2006:15:04:05 -0700

  # Nginx error logs
  - job_name: nginx-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-error
          __path__: /var/log/nginx/error.log

  # Application logs from Docker containers
  - job_name: api-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["cach-api-*"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: 'cach-api-(.+)'
        target_label: 'environment'
        replacement: '${1}'
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - replacement: 'api'
        target_label: 'app'

  # Web app logs
  - job_name: webapp-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["cach-agents-*", "cach-distributor-*", "cach-business-*", "cach-admin-*", "cach-lender-*"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: 'cach-([^-]+)-(.+)'
        target_label: 'app'
        replacement: '${1}'
      - source_labels: ['__meta_docker_container_name']
        regex: 'cach-([^-]+)-(.+)'
        target_label: 'environment'
        replacement: '${2}'
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'