global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Nginx metrics (if nginx-prometheus-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s

  # Application metrics
  - job_name: 'cach-api-production'
    static_configs:
      - targets: ['cach_api_production:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'cach-api-staging'
    static_configs:
      - targets: ['cach_api_staging:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MinIO metrics
  - job_name: 'minio-production'
    static_configs:
      - targets: ['cach_minio_production:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s

  - job_name: 'minio-staging'
    static_configs:
      - targets: ['cach_minio_staging:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s

  # PostgreSQL metrics (if postgres-exporter is added)
  - job_name: 'postgres-production'
    static_configs:
      - targets: ['postgres-exporter-production:9187']

  - job_name: 'postgres-staging'
    static_configs:
      - targets: ['postgres-exporter-staging:9187']
