version: '3.8'

services:
  # Agent App - Next.js Application
  cach-agents:
    image: ${IMAGE_NAME:-abc254/cach-agents}:${IMAGE_TAG:-latest}
    container_name: cach-agents-${ENVIRONMENT:-sandbox}
    restart: unless-stopped
    environment:
      - NODE_ENV=${ENVIRONMENT}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    ports:
      - "${AGENT_PORT:-3010}:3000"
    networks:
      - cach-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: local

networks:
  cach-network:
    driver: bridge